In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plot

In [24]:
pd.set_option('display.max_columns', None)

In [5]:
data = pd.read_csv("../Datasets/titanic.csv")
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [12]:
print("all rows:",len(data))
print(data.isnull().sum())
print(data.isnull().mean())

all rows: 1309
pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64
pclass       0.000000
survived     0.000000
name         0.000000
sex          0.000000
age          0.200917
sibsp        0.000000
parch        0.000000
ticket       0.000000
fare         0.000764
cabin        0.774637
embarked     0.001528
boat         0.628724
body         0.907563
home.dest    0.430863
dtype: float64

In [13]:
data['cabin_null'] = np.where(data['cabin'].isnull(), 1,0)

In [25]:

data['cabin_null']

0       0
1       0
2       0
3       0
4       0
       ..
1304    1
1305    1
1306    1
1307    1
1308    1
Name: cabin_null, Length: 1309, dtype: int64

In [20]:
data.groupby(['survived'])['cabin_null'].mean()

survived
0    0.873918
1    0.614000
Name: cabin_null, dtype: float64

In [29]:
data['survived'].value_counts()/len(data)

survived
0    0.618029
1    0.381971
Name: count, dtype: float64

In [41]:
counts = data['survived'].value_counts()
print(counts)

persntages = data['survived'].value_counts(normalize=True) * 100
print(persntages)
print()
summary = pd.DataFrame({
    'count': counts,
    'persntages':persntages
})

print(summary)

survived
0    809
1    500
Name: count, dtype: int64
survived
0    61.802903
1    38.197097
Name: proportion, dtype: float64

          count  persntages
survived
0           809   61.802903
1           500   38.197097

In [42]:
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,cabin_null
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",0
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22,S,11,NaN,"Montreal, PQ / Chesterville, ON",0
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",0
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",0

In [43]:
data['embarked_map'] = data['embarked'].map({
    'C': 'Cherbourg',
    'Q': 'Queenstown',
    'S': 'Southampton'
})

In [44]:
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,cabin_null,embarked_map
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",0,Southampton
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22,S,11,NaN,"Montreal, PQ / Chesterville, ON",0,Southampton
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",0,Southampton
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0,Southampton
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",0,Southampton

In [45]:
data['embarked'].isnull().value_counts()

embarked
False    1307
True        2
Name: count, dtype: int64

In [46]:
data[data['embarked'].isnull()]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,cabin_null,embarked_map
168,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN,6,NaN,NaN,0,NaN
284,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN,6,NaN,"Cincinatti, OH",0,NaN

In [47]:
data = pd.read_csv('../Datasets/loan.csv', usecols=['employment', 'time_employed'])
data.head()

     employment time_employed
0       Teacher     <=5 years
1    Accountant     <=5 years
2  Statistician     <=5 years
3         Other     <=5 years
4    Bus driver      >5 years

In [50]:
data.isnull().mean()

employment       0.0611
time_employed    0.0529
dtype: float64

In [55]:
print("number of employments: {} ". format(len(data['employment'].unique())))

print(data['employment'].unique())

print(data['time_employed'].unique())

number of employments: 12
['Teacher' 'Accountant' 'Statistician' 'Other' 'Bus driver' 'Secretary'
 'Software developer' 'Nurse' 'Taxi driver' nan 'Civil Servant' 'Dentist']
['<=5 years' '>5 years' nan]

In [56]:
data['employment'].isnull().value_counts()

employment
False    9389
True      611
Name: count, dtype: int64

In [57]:
data['time_employed'].isnull().value_counts()

time_employed
False    9471
True      529
Name: count, dtype: int64

In [ ]:
t = data[data['employment'].isnull()]
print(t.head())

print(len(t))
print(len(data))

t = data[~data['employment'].isnull()]
print(len(t))

   employment time_employed
13        NaN           NaN
17        NaN           NaN
26        NaN           NaN
79        NaN           NaN
86        NaN           NaN
611
10000
9389

In [69]:
count = data[data['employment'].isnull() & data['time_employed'].isnull()]
count

     employment time_employed
13          NaN           NaN
17          NaN           NaN
26          NaN           NaN
79          NaN           NaN
86          NaN           NaN
...         ...           ...
9851        NaN           NaN
9870        NaN           NaN
9885        NaN           NaN
9979        NaN           NaN
9988        NaN           NaN

[524 rows x 2 columns]

In [2]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import roc_auc_score

In [3]:
df_titanic = pd.read_csv("../Datasets/titanic.csv")
df_titanic.head()

   pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [ ]:
print("Number of catagorical variables in dataset: {}".format(len(df_titanic)))

print("Number of catagorical variables in Name: {}".format(len(df_titanic['name'].unique())))

print("Number of catagorical variables in sex: {}".format(len(df_titanic['sex'].unique())))

print("Number of catagorical variables in cabin: {}".format(len(df_titanic['cabin'].unique())))

print("Number of catagorical variables in embarked: {}".format(len(df_titanic['embarked'].unique())))

print("Number of catagorical variables in ticket: {}".format(len(df_titanic['ticket'].unique())))

Number of catagorical variables in dataset: 1309
Number of catagorical variables in Name: 1307