In [73]:
import pandas as pd 

from sklearn.linear_model import LogisticRegression


from sklearn.model_selection import train_test_split

In [74]:
df = pd.read_csv("../Datasets/titanic.csv")

df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [75]:
print('number of catgorical variables in name {}'.format(df['name'].unique().size))
print(f'number of catgorical variables in sex : {len(df["sex"].unique())}')
print(f"number of catgorical variables in embarked : {df['embarked'].value_counts()}")
print(f"number of catgorical variables in embarked : {df['embarked'].unique().size}")
print(f"number of catgorical variables in embarked : {len(df['embarked'].unique())}")
print(f"number of catgorical variables in embarked : {df['embarked'].unique()}")
print(f"number of catgorical variables in cabin : {df['cabin'].nunique()}")
print(f"number of catgorical variables in ticket : {df['ticket'].nunique()}")
print(f"number of catgorical variables in ticket : {df['ticket'].value_counts()}")

number of catgorical variables in name 1307
number of catgorical variables in sex : 2
number of catgorical variables in embarked : embarked
S    914
C    270
Q    123
Name: count, dtype: int64
number of catgorical variables in embarked : 4
number of catgorical variables in embarked : 4
number of catgorical variables in embarked : ['S' 'C' nan 'Q']
number of catgorical variables in cabin : 181
number of catgorical variables in ticket : 929
number of catgorical variables in ticket : ticket
CA. 2343        11
CA 2144          8
1601             8
347082           7
S.O.C. 14879     7
                ..
349202           1
347466           1
347075           1
350043           1
348125           1
Name: count, Length: 929, dtype: int64

In [76]:
print(df['cabin'].unique())
print()
print(df['ticket'].value_counts())

['B5' 'C22' 'E12' 'D7' 'A36' 'C101' nan 'C62' 'B35' 'A23' 'B58' 'D15' 'C6'
 'D35' 'C148' 'C97' 'B49' 'C99' 'C52' 'T' 'A31' 'C7' 'C103' 'D22' 'E33'
 'A21' 'B10' 'B4' 'E40' 'B38' 'E24' 'B51' 'B96' 'C46' 'E31' 'E8' 'B61'
 'B77' 'A9' 'C89' 'A14' 'E58' 'E49' 'E52' 'E45' 'B22' 'B26' 'C85' 'E17'
 'B71' 'B20' 'A34' 'C86' 'A16' 'A20' 'A18' 'C54' 'C45' 'D20' 'A29' 'C95'
 'E25' 'C111' 'C23' 'E36' 'D34' 'D40' 'B39' 'B41' 'B102' 'C123' 'E63'
 'C130' 'B86' 'C92' 'A5' 'C51' 'B42' 'C91' 'C125' 'D10' 'B82' 'E50' 'D33'
 'C83' 'B94' 'D49' 'D45' 'B69' 'B11' 'E46' 'C39' 'B18' 'D11' 'C93' 'B28'
 'C49' 'B52' 'E60' 'C132' 'B37' 'D21' 'D19' 'C124' 'D17' 'B101' 'D28' 'D6'
 'D9' 'B80' 'C106' 'B79' 'C47' 'D30' 'C90' 'E38' 'C78' 'C30' 'C118' 'D36'
 'D48' 'D47' 'C105' 'B36' 'B30' 'D43' 'B24' 'C2' 'C65' 'B73' 'C104' 'C110'
 'C50' 'B3' 'A24' 'A32' 'A11' 'A10' 'B57' 'C28' 'E44' 'A26' 'A6' 'A7'
 'C31' 'A19' 'B45' 'E34' 'B78' 'B50' 'C87' 'C116' 'C55' 'D50' 'E68' 'E67'
 'C126' 'C68' 'C70' 'C53' 'B19' 'D46' 'D37' 'D26' 'C32' 'C80' 'C82' 'C128'
 'E39' 'D' 'F4' 'D56' 'F33' 'E101' 'E77' 'F2' 'D38' 'F' 'E121' 'E10' 'G6'
 'F38']

ticket
CA. 2343        11
CA 2144          8
1601             8
347082           7
S.O.C. 14879     7
                ..
349202           1
347466           1
347075           1
350043           1
348125           1
Name: count, Length: 929, dtype: int64

In [77]:
df['cabin_reduced'] = df['cabin'].str.extract(r'([A-za-z]+)',expand=False)
df[['cabin', 'cabin_reduced']].head()

  cabin cabin_reduced
0    B5             B
1   C22             C
2   C22             C
3   C22             C
4   C22             C

In [78]:
print(df['cabin_reduced'].value_counts())
print(len(df['cabin_reduced'].unique()))
print(f"nuber of catagorical value in cabin is: {len(df['cabin'].unique())}")

cabin_reduced
C    94
B    65
D    46
E    41
A    22
F    21
G     5
T     1
Name: count, dtype: int64
9
nuber of catagorical value in cabin is: 182

In [79]:
used_cols =['cabin','cabin_reduced', 'sex']

X_train, X_test, Y_train, Y_test = train_test_split(
    df[used_cols],
    df['survived'],

    test_size=0.3,
    random_state=0
)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(916, 3)
(393, 3)
(916,)
(393,)

In [80]:
# get the unseen data in the train set
unsen_data_train = X_train[~X_train['cabin_reduced'].isin(X_test['cabin_reduced'])]
print(len(unsen_data_train))

1

In [81]:
unsen_data_train = [x for x in X_train['cabin_reduced'].unique() if x not in X_test['cabin_reduced'].unique() ]

print(len(unsen_data_train))

2

In [82]:
unsen_data_train = [x for x in X_train['cabin'].unique() if x not in X_test['cabin'].unique() ]

print(len(unsen_data_train))

113

In [83]:
unsen_data_train = [x for x in X_test['cabin'].unique() if x not in X_train['cabin'].unique() ]
print(len(unsen_data_train))

36

In [84]:
unseen_data_test = []

for x in X_test['cabin']:
    # Skip NaN values
    if pd.notna(x) and x not in X_train['cabin'].values:
        unseen_data_test.append(x)

print(len(unseen_data_test))

41

In [85]:
unseen_data_test = []

for x in X_test['cabin'].unique():
    # Skip NaN values
    if  x not in X_train['cabin'].values:
        unseen_data_test.append(x)

print(len(unseen_data_test))

36

In [86]:
# encode cabin 

dic_cabin_reduced = {k: i for i, k in enumerate(df['cabin_reduced'].unique(),0)}
dic_cabin_reduced

{'B': 0, 'C': 1, 'E': 2, 'D': 3, 'A': 4, nan: 5, 'T': 6, 'F': 7, 'G': 8}

In [87]:
df['cabin_mapped_reduced'] = df['cabin'].map(dic_cabin_reduced)
X_train['cabin_mapped_reduced'] = X_train['cabin_reduced'].map(dic_cabin_reduced)
X_test['cabin_mapped_reduced'] = X_test['cabin_reduced'].map(dic_cabin_reduced)

In [88]:
dic_cabin_not_reduced = {
    k:i for i,k in enumerate(df['cabin'].unique(),0)
}


df['cabin_mapped_not_reduced'] = df['cabin'].map(dic_cabin_not_reduced)
X_train['cabin_mapped_not_reduced'] = X_train['cabin'].map(dic_cabin_not_reduced)
X_test['cabin_mapped_not_reduced']= X_test['cabin'].map(dic_cabin_not_reduced)
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,cabin_reduced,cabin_mapped_reduced,cabin_mapped_not_reduced
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",B,NaN,0
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22,S,11,NaN,"Montreal, PQ / Chesterville, ON",C,NaN,1
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",C,NaN,1
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",C,NaN,1
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",C,NaN,1

In [89]:
X_train.head()

,cabin,cabin_reduced,sex,cabin_mapped_reduced,cabin_mapped_not_reduced
501,NaN,NaN,female,5,6
588,NaN,NaN,female,5,6
402,NaN,NaN,female,5,6
1193,NaN,NaN,male,5,6
686,NaN,NaN,female,5,6

In [90]:
#cheek it there is any missing values in cappin mapped
X_train[['cabin_mapped_reduced','cabin_reduced','sex']].isnull().sum()

cabin_mapped_reduced      0
cabin_reduced           702
sex                       0
dtype: int64